commerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'commerce.views.splash', name='splash'),
    url(r'^home$', 'commerce.views.index', name='index'),
    # url(r'^$', 'commerce.views.index', name='index'),
    url(r'^information/$', 'commerce.views.information', name='information'),    
    url(r'^condition/$', 'commerce.views.condition', name='condition'),    
    
    url(r'^category/$', 'commerce.views.display_category_random', name='display_category_random'),
    url(r'^category/(?P<category_id>\d+)/$', 'commerce.views.display_category', name='display_category'),
    url(r'^product-min-price/$', 'commerce.views.display_product_min_price', name='display_product_min_price'),
    url(r'^product-min-moq/$', 'commerce.views.display_product_min_moq', name='display_product_min_moq'),
    url(r'^product/(?P<product_id>\d+)/$', 'commerce.views.display_product', name='display_product'),
    
    url(r'^account/profile/$', 'commerce.views.account', name='account'),
    url(r'^order/$', 'commerce.views.display_order', name='display_order'),
    url(r'^add-address/$', 'commerce.views.add_address', name='add_address'),
    url(r'^addresses/$', 'commerce.views.addresses', name='addresses'),
    url(r'^remove-addresses/(?P<address_id>\d+)/$', 'commerce.views.remove_address', name='remove_address'),
    
    url(r'^cart/(?P<product_id>\d+)/(?P<qty>\d+)/$', 'commerce.views.add_to_cart', name='cart'),
#     url(r'^remove-from-cart/(?P<product_id>\d+)/$', 'commerce.views.remove_from_cart', name='remove_from_cart'),
    url(r'^shipping/(?P<product_id>\d+)/$', 'commerce.views.shipping', name='shipping'),
    
    url(r'^shipping-special/$', 'commerce.views.shipping_special', name='shipping_special'),
    
    url(r'print-contrat/(?P<order_id>\d+)/$', 'commerce.views.print_contrat', name='print_contrat'),
    
    url(r'^display-users/$', 'commerce.views.display_users', name='display_users'),
    url(r'^display-user-order/(?P<id>\d+)/$', 'commerce.views.display_users_order', name='display_users_order'),
    url(r'^display-users-order/special/$', 'commerce.views.display_users_order_special', name='display_users_order_special'),
    url(r'^display-user-order/special/validate/(?P<id>\d+)/$', 'commerce.views.users_order_special_validate', name='users_order_special_validate'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

okayproject/urls.py
from commerce.views import SignUpView, SignOutView, SignInView

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^account/sign-in/$', SignInView.as_view(), name='sign_in'),
    url(r'^account/sign-up/$', SignUpView.as_view(), name='sign_up'),
    url(r'^account/sign-out/$', SignOutView.as_view(), name='sign_out'),
    
    url(r'', include('commerce.urls', namespace='commerce', app_name='commerce')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

from commerce.models import Address, OrderSpecial

class UsersCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=100, required=True)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email',]

class AddAddress(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
        exclude = ['user']

class AddParticularAddress(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    cin = forms.CharField(required=False)
    
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
        exclude = ['user', 'company', 'company_form', 'nif']

class AddSocietyAddress(forms.ModelForm):
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    nif = forms.CharField(required=False)
    
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
#         fields = '__all__'
        exclude = ['user', 'gender', 'first_name', 'last_name', 'cin']
        

class OrderSpecialForm(forms.ModelForm):
#     name = forms.CharField(max_length=100, required=True)
#     short_desc = forms.CharField(max_length=100, required=False)
#     long_desc = forms.CharField(max_length=100, required=False)
     
    class Meta:
        model = OrderSpecial
        fields = ['name', 'short_desc', 'long_desc', 'quantity', 'thumbnail',]
        exclude = ['user']

commerce/views.py
# -*- coding:utf-8 -*-

from commerce.models import *
from commerce.forms import *

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse

from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
from io import BytesIO
from django.contrib.auth.models import User

import datetime
import random
from datetime import date
import time

# Create your views here.

def slide_all_product():
    products = list()
    count = Product.objects.count()
    p = Product.objects.order_by('price').filter(date_validity__gte=datetime.datetime.now())
    i = 0
    while i < count:
        products.append(p[i:(i+3)])
        i += 3

    return products

def initialize_product_data():
    products = Product.objects.all()
    for product in products:
        if datetime.date.today().__ge__(product.date_validity):
            product.qty_commanded = 0
            product.save()

def splash(request):
    return render(request, 'spash.html')

def index(request):
    products = Product.objects.order_by('-id').filter(date_validity__gte=datetime.datetime.now())
    products_slide = slide_all_product()
    categories_list = Category.objects.all()

    address_count = Address.objects.filter(user_id=request.user.id).count()
    if request.user.is_authenticated():
        if request.user.is_superuser:
            user_count = User.objects.all().count() - 1
            orders = Order.objects.order_by('-id').filter()
            orders_valide = Order.objects.filter(status='Valide').order_by('-date_validated')
            orders_waite = Order.objects.filter(status='En attente').order_by('-date_validated')
            initialize_product_data()
            return render(request, 'admin_okay/index.html', locals())
        else:
            order_special = OrderSpecial.objects.filter(user_id=request.user.id, status='Valide').count()
            if order_special > 0:
                messages.add_message(request, messages.INFO, "Vous avez des commandes spéciale validé <br>\
                Nous vous informons par e-mail la suite de votre commande spéciale")
    
    return render(request, 'index.html', locals())

# -------------------------------------
# user connexion
# -------------------------------------

def information(request):
    products = Product.objects.filter(date_validity__lte=datetime.datetime.now()).order_by('-id')[:6]
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    return render(request, 'information.html', locals())

def condition(request):
    products = Product.objects.filter(date_validity__lte=datetime.datetime.now()).order_by('-id')[:6]
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    return render(request, 'condition.html', locals())

class SignUpView(generic.CreateView):
    form_class = UsersCreationForm
    model = User
    success_url = reverse_lazy('commerce:index')
    template_name = 'account/sign_up.html'
    
    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO,
                             'Vous ête actuellement membre du site! Connectez à votre compte à fin d\'effectuer des commandes')
        return super(SignUpView, self).form_valid(form)
    
class SignInView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('commerce:index')
    template_name = 'account/sign_in.html'
    
    
    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        
        if user is not None and user.is_active:
            login(self.request, user)
            return super(SignInView, self).form_valid(form)
        else:
            return self.form_invalid(form)
        
class SignOutView(generic.RedirectView):
    url = reverse_lazy('sign_in')
    
    def get(self, request):
        logout(request)
        return super(SignOutView, self).get(request)

def account(request):
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.username = request.POST['username']
        
#         if user.check_password(request.POST['password1']):
#             user.set_password(request.POST['password2'])
#         else:
#             messages.add_message(request, messages.ERROR, "Password invalide. Veuillez saisir votre ancien password")
        
        user.save()
        
    return render(request, 'account/account.html', locals())

# product & category

def display_category(request, category_id):
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    category = get_object_or_404(Category, pk=category_id)
    product_list = category.all_products()
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/category.html', locals())

def display_category_random(request):
    categories_list = Category.objects.all()
    x = random.randint(0, categories_list.count()-1)
    category_id = categories_list[x].id
    category = get_object_or_404(Category, pk=category_id)
    product_list = category.all_products()
    paginator = Paginator(product_list, 4)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/category.html', locals())

def display_product_min_price(request):
    title = 'Produits moins chère'
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
#     product_list = Product.objects.order_by('price')
    product_list = Product.objects.order_by('price').filter(date_validity__gte=datetime.datetime.now())
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/product_min.html', locals())

def display_product_min_moq(request):
    title = 'Produit avec une MOQ minimum'
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
#     product_list = Product.objects.order_by('moq')
    product_list = Product.objects.order_by('moq').filter(date_validity__gte=datetime.datetime.now())
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/product_min.html', locals())


def display_product(request, product_id):
#     id = request.session['cart'].get('product_qty')
    product = get_object_or_404(Product, pk=product_id) 
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    
    if request.method == 'POST':
        quantity = request.POST['quantity']        
        if Cart.objects.filter(user_id=request.user.id, product_id=product_id).exists():
            cart = Cart.objects.get(user_id=request.user.id, product_id=product_id)
            cart.quantity = request.POST['quantity']
        else:
            cart = Cart(user_id=request.user.id, product_id=product_id, quantity=int(request.POST['quantity']))

        cart.save()
                
        return render(request, 'commerce/cart.html', locals())
    
    return render(request, 'commerce/product.html', locals())

# orders

def confirmation(request):
    pass

def shipping(request, product_id):
    categories_list = Category.objects.all()
    addresses = Address.objects.filter(user_id=request.user.id)
    cart = Cart.objects.get(user_id=request.user.id, product_id=product_id)
    
    if request.method == 'POST':
        order = Order(product_id=product_id,
                      user_id=request.user.id,
                      address_id=request.POST['shipping_address'],
                      quantity=cart.quantity)
        
        product = Product.objects.get(id=product_id)

commerce/templates/admin_okay/order-special.html
{% extends "layout.html" %}

{% block title %}Commande spécial{% endblock %}

{% block content %}
<section id="cart_items">
    <div class="container">
        <div class="row">
            {% include "admin_okay/side-bar.html" %}            
            <div class="col-sm-9 padding-right">
                <div class="table-responsive cart_info">
                    
                    <table class="table table-condensed">
                        <thead>
                            <tr class="cart_menu">
                                <td class="quantity">Pseudo</td>
                                <td class="price">e-mail</td>
                                <td class="price">Produit</td>
                                <td class="price">Description</td>
                                <td class="price">Quantité</td>
                                <td class="price"></td>
                            </tr>
                        </thead>
                        <tbody>
                            <!--  -->
                            {% for order in orders %}
                                <tr>
                                    <td class="">
                                        <a href="{% url 'commerce:display_users_order' order.user.id %}">
                                        <span class="glyphicon glyphicon-user"></span> {{ order.user.username }}
                                        </a>
                                    </td>
                                    <td class="">{{ order.user.first_name }}</td>
                                    <td class="">{{ order.name }}</td>
                                    <td class="">{{ order.short_desc }}</td>
                                    <td class="">{{ order.quantity }}</td>
                                    <td class="">
                                        {% if order.status == 'En attente' %}                                            
                                            <a href="{% url 'commerce:users_order_special_validate' order.id %}" class="text-info"><span class="glyphicon glyphicon-ok"></span></a> |                                     
                                            <a href="#" class="text-danger"><span class="glyphicon glyphicon-remove"></span></a>
                                        {% endif %}
                                    </td>                                    
                                </tr>
                            {% empty %}
                            {% endfor %}
                        <!--  -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
</section>
<!--  -->
        

{% endblock %}

commerce/templates/admin_okay/side-bar.html
{% load static %}

<div class="col-sm-3">
    <div class="left-sidebar"> 
            {% comment %}      
            <!-- categories -->
            <div class="panel panel-default">
                <div class="panel-heading">
                        <h3 class="panel-title">
                            <a class="accordion-toggle" href="#item-category" data-toggle="collapse">
                                <h4>Offres<span class="glyphicon glyphicon-chevron-right pull-right"></span></h4>
                            </a>
                        </h3>
                </div>
                <div id="item-category" class="collapse in">
                    <div class="list-group">
                    {% for category in categories_list %}
                        <a class="list-group-item" href="{% url 'commerce:display_category' category.id %}">{{ category.name }}</a>
                    {% empty %}
                    {% endfor %}
                    </div>
                </div>
            </div>
            {% endcomment %}
            <!-- account -->
            {% if user.is_authenticated %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <a class="accordion-toggle" href="#item-account" data-toggle="collapse">
                            <h4>Statistique<span class="glyphicon glyphicon-chevron-right pull-right"></span></h4>
                        </a>
                    </h3>
                </div>
                <div id="item-account" class="collapse in">
                    <div class="list-group">
                        <a class="list-group-item " href="{% url 'commerce:display_users' %}">
                            Liste des client
                            <span class="badge">{{ user_count }}</span>
                        </a>
                        <a class="list-group-item " href="{% url 'commerce:index' %}">Commandes</a>
                        <a class="list-group-item " href="{% url 'commerce:display_users_order_special' %}">Commandes speciales</a>
                    </div>
                </div>
            </div>
            {% endif %}
            
            <div class="panel">
                <img src="{% static 'images/home/shipping.jpg' %}" alt="" />
            </div>
            
    </div>
</div>

commerce/templates/admin_okay/user_list.html
{% extends "layout.html" %}

{% block title %}Liste des clients{% endblock %}

{% block content %}
<section id="cart_items">
    <div class="container">
        <div class="row">
            {% include "admin_okay/side-bar.html" %}            
            <div class="col-sm-9 padding-right">
                <div class="table-responsive cart_info">
                    
                    <table class="table table-condensed">
                        <thead>
                            <tr class="cart_menu">
                                <td class="image">Nom</td>
                                <td class="description">Prénom</td>
                                <td class="price">e-mail</td>
                                <td class="quantity">Pseudo</td>
                            </tr>
                        </thead>
                        <tbody>
                            <!--  -->
                            {% for user1 in users %}
                                {% if not user1.is_superuser %}
                                <tr>
                                    <td class="cart_total">
                                        <a href="{% url 'commerce:display_users_order' user1.id %}">
                                        {{ user1.username }}
                                        </a>
                                    </td>
                                    <td class="cart_price">{{ user1.last_name }}</td>
                                    <td class="cart_quantity">{{ user1.first_name }}</td>
                                    <td class="cart_total">{{ user1.email }}</td>
                                </tr>
                                {% endif %}
                            {% empty %}
                            {% endfor %}
                        <!--  -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
</section>
<!--  -->
        

{% endblock %}