commerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'commerce.views.splash', name='splash'),
    url(r'^home$', 'commerce.views.index', name='index'),
    # url(r'^$', 'commerce.views.index', name='index'),
    url(r'^information/$', 'commerce.views.information', name='information'),    
    url(r'^condition/$', 'commerce.views.condition', name='condition'),    
    
    url(r'^category/$', 'commerce.views.display_category_random', name='display_category_random'),
    url(r'^category/(?P<category_id>\d+)/$', 'commerce.views.display_category', name='display_category'),
    url(r'^product-min-price/$', 'commerce.views.display_product_min_price', name='display_product_min_price'),
    url(r'^product-min-moq/$', 'commerce.views.display_product_min_moq', name='display_product_min_moq'),
    url(r'^product/(?P<product_id>\d+)/$', 'commerce.views.display_product', name='display_product'),
    
    url(r'^account/profile/$', 'commerce.views.account', name='account'),
    url(r'^order/$', 'commerce.views.display_order', name='display_order'),
    url(r'^add-address/$', 'commerce.views.add_address', name='add_address'),
    url(r'^addresses/$', 'commerce.views.addresses', name='addresses'),
    url(r'^remove-addresses/(?P<address_id>\d+)/$', 'commerce.views.remove_address', name='remove_address'),
    
    url(r'^cart/(?P<product_id>\d+)/(?P<qty>\d+)/$', 'commerce.views.add_to_cart', name='cart'),
#     url(r'^remove-from-cart/(?P<product_id>\d+)/$', 'commerce.views.remove_from_cart', name='remove_from_cart'),
    url(r'^shipping/(?P<product_id>\d+)/$', 'commerce.views.shipping', name='shipping'),
    
    url(r'^shipping-special/$', 'commerce.views.shipping_special', name='shipping_special'),
    
    url(r'print-contrat/(?P<order_id>\d+)/$', 'commerce.views.print_contrat', name='print_contrat'),
    
    url(r'^display-users/$', 'commerce.views.display_users', name='display_users'),
    url(r'^display-user-order/(?P<id>\d+)/$', 'commerce.views.display_users_order', name='display_users_order'),
    url(r'^display-users-order/special/$', 'commerce.views.display_users_order_special', name='display_users_order_special'),
    url(r'^display-user-order/special/validate/(?P<id>\d+)/$', 'commerce.views.users_order_special_validate', name='users_order_special_validate'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

okayproject/urls.py
from commerce.views import SignUpView, SignOutView, SignInView

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^account/sign-in/$', SignInView.as_view(), name='sign_in'),
    url(r'^account/sign-up/$', SignUpView.as_view(), name='sign_up'),
    url(r'^account/sign-out/$', SignOutView.as_view(), name='sign_out'),
    
    url(r'', include('commerce.urls', namespace='commerce', app_name='commerce')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

from commerce.models import Address, OrderSpecial

class UsersCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=100, required=True)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email',]

class AddAddress(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
        exclude = ['user']

class AddParticularAddress(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    cin = forms.CharField(required=False)
    
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
        exclude = ['user', 'company', 'company_form', 'nif']

class AddSocietyAddress(forms.ModelForm):
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    nif = forms.CharField(required=False)
    
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
#         fields = '__all__'
        exclude = ['user', 'gender', 'first_name', 'last_name', 'cin']
        

class OrderSpecialForm(forms.ModelForm):
#     name = forms.CharField(max_length=100, required=True)
#     short_desc = forms.CharField(max_length=100, required=False)
#     long_desc = forms.CharField(max_length=100, required=False)
     
    class Meta:
        model = OrderSpecial
        fields = ['name', 'short_desc', 'long_desc', 'quantity', 'thumbnail',]
        exclude = ['user']

commerce/views.py
# -*- coding:utf-8 -*-

from commerce.models import *
from commerce.forms import *

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse

from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
from io import BytesIO
from django.contrib.auth.models import User

import datetime
import random
from datetime import date
import time

# Create your views here.

def slide_all_product():
    products = list()
    count = Product.objects.count()
    p = Product.objects.order_by('price').filter(date_validity__gte=datetime.datetime.now())
    i = 0
    while i < count:
        products.append(p[i:(i+3)])
        i += 3

    return products

def initialize_product_data():
    products = Product.objects.all()
    for product in products:
        if datetime.date.today().__ge__(product.date_validity):
            product.qty_commanded = 0
            product.save()

def splash(request):
    return render(request, 'spash.html')

def index(request):
    products = Product.objects.order_by('-id').filter(date_validity__gte=datetime.datetime.now())
    products_slide = slide_all_product()
    categories_list = Category.objects.all()

    address_count = Address.objects.filter(user_id=request.user.id).count()
    if request.user.is_authenticated():
        if request.user.is_superuser:
            user_count = User.objects.all().count() - 1
            orders = Order.objects.order_by('-id').filter()
            orders_valide = Order.objects.filter(status='Valide').order_by('-date_validated')
            orders_waite = Order.objects.filter(status='En attente').order_by('-date_validated')
            initialize_product_data()
            return render(request, 'admin_okay/index.html', locals())
        else:
            order_special = OrderSpecial.objects.filter(user_id=request.user.id, status='Valide').count()
            if order_special > 0:
                messages.add_message(request, messages.INFO, "Vous avez des commandes spéciale validé <br>\
                Nous vous informons par e-mail la suite de votre commande spéciale")
    
    return render(request, 'index.html', locals())

# -------------------------------------
# user connexion
# -------------------------------------

def information(request):
    products = Product.objects.filter(date_validity__lte=datetime.datetime.now()).order_by('-id')[:6]
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    return render(request, 'information.html', locals())

def condition(request):
    products = Product.objects.filter(date_validity__lte=datetime.datetime.now()).order_by('-id')[:6]
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    return render(request, 'condition.html', locals())

class SignUpView(generic.CreateView):
    form_class = UsersCreationForm
    model = User
    success_url = reverse_lazy('commerce:index')
    template_name = 'account/sign_up.html'
    
    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO,
                             'Vous ête actuellement membre du site! Connectez à votre compte à fin d\'effectuer des commandes')
        return super(SignUpView, self).form_valid(form)
    
class SignInView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('commerce:index')
    template_name = 'account/sign_in.html'
    
    
    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        
        if user is not None and user.is_active:
            login(self.request, user)
            return super(SignInView, self).form_valid(form)
        else:
            return self.form_invalid(form)
        
class SignOutView(generic.RedirectView):
    url = reverse_lazy('sign_in')
    
    def get(self, request):
        logout(request)
        return super(SignOutView, self).get(request)

def account(request):
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.username = request.POST['username']
        
#         if user.check_password(request.POST['password1']):
#             user.set_password(request.POST['password2'])
#         else:
#             messages.add_message(request, messages.ERROR, "Password invalide. Veuillez saisir votre ancien password")
        
        user.save()
        
    return render(request, 'account/account.html', locals())

# product & category

def display_category(request, category_id):
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    category = get_object_or_404(Category, pk=category_id)
    product_list = category.all_products()
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/category.html', locals())

def display_category_random(request):
    categories_list = Category.objects.all()
    x = random.randint(0, categories_list.count()-1)
    category_id = categories_list[x].id
    category = get_object_or_404(Category, pk=category_id)
    product_list = category.all_products()
    paginator = Paginator(product_list, 4)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/category.html', locals())

def display_product_min_price(request):
    title = 'Produits moins chère'
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
#     product_list = Product.objects.order_by('price')
    product_list = Product.objects.order_by('price').filter(date_validity__gte=datetime.datetime.now())
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/product_min.html', locals())

def display_product_min_moq(request):
    title = 'Produit avec une MOQ minimum'
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
#     product_list = Product.objects.order_by('moq')
    product_list = Product.objects.order_by('moq').filter(date_validity__gte=datetime.datetime.now())
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/product_min.html', locals())


def display_product(request, product_id):
#     id = request.session['cart'].get('product_qty')
    product = get_object_or_404(Product, pk=product_id) 
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    
    if request.method == 'POST':
        quantity = request.POST['quantity']        
        if Cart.objects.filter(user_id=request.user.id, product_id=product_id).exists():
            cart = Cart.objects.get(user_id=request.user.id, product_id=product_id)
            cart.quantity = request.POST['quantity']
        else:
            cart = Cart(user_id=request.user.id, product_id=product_id, quantity=int(request.POST['quantity']))

        cart.save()
                
        return render(request, 'commerce/cart.html', locals())
    
    return render(request, 'commerce/product.html', locals())

# orders

def confirmation(request):
    pass

def shipping(request, product_id):
    categories_list = Category.objects.all()
    addresses = Address.objects.filter(user_id=request.user.id)
    cart = Cart.objects.get(user_id=request.user.id, product_id=product_id)
    
    if request.method == 'POST':
        order = Order(product_id=product_id,
                      user_id=request.user.id,
                      address_id=request.POST['shipping_address'],
                      quantity=cart.quantity)
        
        product = Product.objects.get(id=product_id)

commerce/templates/condition.html
{% extends "layout.html" %}


{% block title %}Terme et condition de vente{% endblock %}

{% block content %}
        
    {% load staticfiles %}

<section><!--slider-->
    <div class="container">
        <div class="row">
            {% include "side-bar.html" %}
            <div class="col-sm-9">
                <h2 class="title text-center">Termes et Conditions</h2>
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <article>
                            <h1>Article 1</h1>
                            <ol>
                                <li></li>
                                <li></li>
                                <li></li>
                            </ol>
                        </article>
                        <hr>
                        <article>
                            <h1>Article 2</h1>
                            <ol>
                                <li></li>
                                <li></li>
                                <li></li>
                            </ol>
                        </article>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</section><!--/slider-->
    
{% endblock %}

commerce/templates/index.html
{% extends "layout.html" %}


{% block content %}
        
    <section>
        <div class="container">
            <div class="row">
                {% include "side-bar.html" %}                
                
                <div class="col-sm-9 padding-right">
                    <div class="features_items"><!--features_items-->
                    
                            
                        {% include "includes/slider.html" %}
                        <br>
                        <br>
                        <h2 class="title text-center">Derniers produits</h2>
                        <div class="row">    
                             {% for product in products %}
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            <img class="produit-thumbnail thumbnail" src="{{ MEDIA_URL }}{{ product.thumbnail }}"  class="thumbnail" alt="" />
                                            <h2>{{ product.price }} MGA</h2>
                                            <p class="product-name" >{{ product.name }}</p>
                                        </div>
                                        <div class="product-overlay">
                                            <div class="overlay-content">
                                                <p class="product-name">MOQ : {{ product.moq }} [{{ product.get_moq_restant }} restant]</p>
                                                <h2>{{ product.price }} MGA</h2>
                                                <p class="product-name">{{ product.name }}</p>
                                                <a href="{% url 'commerce:display_product' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-eye -open"></i>Details / Commandes</a>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                            {% empty %}
                            {% endfor %}
                        </div>
                    </div><!--features_items-->
                
                        <!-- fnin du boucle nos poduit disponibles -->          
                    {% include "recommended-product.html" %}
                    
                </div>
            </div>
        </div>
    </section>

{% endblock %}

commerce/templates/recommended-product.html
{% load staticfiles %}

<div class="recommended_items col-lg-12"><!--recommended_items-->
    <h2 class="title text-center">Produits recommendés</h2>
    
    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            {% for products in products_slide %}
                {% ifequal products products_slide|first %}                                    
                <div class="item active">
                {% else %}
                <div class="item">
                {% endifequal %}                            
                {% for product in products %}
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="productinfo text-center">
                                <img class="img1" src="{{ MEDIA_URL }}{{ product.thumbnail }}" alt="" />
                                <h4 class="product-name">{{ product.name|truncatechars:25 }}</h4>
                                <a href="{% url 'commerce:display_product' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Détails</a>
                            </div>
                        </div>
                    </div>
                                                          
                {% empty %}
                {% endfor %}
                </div>
            {% endfor %}
        </div>
        <div>
            <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>
    
</div><!--/recommended_items-->

commerce/templates/side-bar.html
{% load static %}

<div class="col-sm-3">
    <div class="left-sidebar">       
            <!-- categories -->
            <div class="panel panel-default">
                <div class="panel-heading">
                        <h3 class="panel-title">
                            <a class="accordion-toggle" href="#item-category" data-toggle="collapse">
                                <h4>Categories<span class="glyphicon glyphicon-chevron-right pull-right"></span></h4>
                            </a>
                        </h3>
                </div>
                <div id="item-category" class="collapse in">
                    <div class="list-group">
                    {% for category in categories_list %}
                        <a class="list-group-item" href="{% url 'commerce:display_category' category.id %}">{{ category.name }}</a>
                    {% empty %}
                    {% endfor %}
                    </div>
                </div>
                <div class="panel-footer">
                    <a class="" href="{% url 'commerce:index' %}">
                        Derniers produits
                        <span class="glyphicon glyphicon-star pull-right"></span>
                    </a>
                </div>
            </div>
            <!-- filtre -->
            <div class="panel panel-default">
                <div class="panel-heading">
                        <h3 class="panel-title">
                            <a class="accordion-toggle" href="#item-offres" data-toggle="collapse">
                                <h4>Nos offres<span class="glyphicon glyphicon-chevron-right pull-right"></span></h4>
                            </a>
                        </h3>
                </div>
                <div id="item-offres" class="collapse in">
                    <div class="list-group">
                    <a class="list-group-item" href="{% url 'commerce:display_product_min_price' %}">Moins chers</a>
                    <a class="list-group-item" href="{% url 'commerce:display_product_min_moq' %}">MOQ minimum</a>
                    </div>
                </div>
                <div class="panel-footer">
                    <a class="" href="{% url 'commerce:shipping_special' %}">
                        Commande spéciale
                        <span class="glyphicon glyphicon-star pull-right"></span>
                    </a>
                </div>
            </div>
            <!-- account -->
            {% if user.is_authenticated %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <a class="accordion-toggle" href="#item-account" data-toggle="collapse">
                            <h4>Espace client<span class="glyphicon glyphicon-chevron-right pull-right"></span></h4>
                        </a>
                    </h3>
                </div>
                <div id="item-account" class="collapse in">
                    <div class="list-group">
                        <a class="list-group-item " href="{% url 'commerce:account' %}">Mon compte</a>
                        <a class="list-group-item " href="{% url 'commerce:addresses' %}">
                            Mes renseignements
                            <span class="badge">{{ address_count }}</span>
                        </a>
                        <a class="list-group-item " href="{% url 'commerce:display_order' %}">Mes commandes</a>
                    </div>
                </div>
            </div>
            {% endif %}
            
            <div class="panel">
                <img src="{% static 'images/home/shipping.jpg' %}" alt="" />
            </div>
            
    </div>
</div>

commerce/templates/spash.html
{% load static %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>OKAY</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <!-- FONT AWESOME CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- ANIMATE  CSS -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
    <!-- PRETTY PHOTO  CSS -->
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet" />
    <!--  STYLE SWITCHER CSS -->
    <link href="{% static 'css/styleSwitcher.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style2.css' %}" rel="stylesheet" />
    <link href="{% static 'css/themes/pink.css' %}" id="mainCSS" rel="stylesheet" />
    <!-- CUSTOM STYLE CSS -->

</head>
<body>
       
    <!--<div class="switcher" style="left:-50px;">
        <a id="switch-panel" class="hide-panel">
            <i class="fa fa-desktop"></i>

        </a>
        <p style="font-size:10px">choose</p>
        <ul class="colors-list">
            <li><a title="Pink" id="pink" class="pink" ></a></li>
            <li><a title="Green" id="green" class="green" ></a></li>
            <li><a title="Blue" id="blue" class="blue" ></a></li>
             <li><a title="Brown" id="brown" class="brown" ></a></li>
           
        </ul>
    </div>	-->
    <!-- /. END THEME SWITCHER-->

    <div id="home-sec">
        <div class="overlay">
            <div class="container">
                <div class="row pad-top-bottom  move-me">
                    <div class="col-lg-5 col-md-5 col-sm-5 text-center">
                        <img src="{% static 'images/home/girl1.jpg' %}" class="main-img img-circle wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".2s" alt=""/>
                        <h1 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".4s">DES PRODUITS</h1>
                        <h2 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".6s">A VOS BESOINS</h2>
                        <a href="{% url 'sign_in' %}" class="btn custom-btn-one btn-lg wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".8s">SE CONNECTER</a>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2 text-center  ">
                        <a href="{% url 'commerce:information' %}" class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".1s">
                            <center><img src="{% static 'images/home/logo.png' %}" width="85%" /></center><!-- <i class="fa fa-info icon-round icon-round-active"></i> -->
                            <h3 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".2s">A PROPOS</h3>
                        </a>
                        <a href="#" class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".3s">
                            <i class="fa icon-round">
                                <span class="glyphicon glyphicon-paperclip"></span>
                            </i>
                            <h3 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".4s">CONDITIONS</h3>
                        </a>
                        {% comment %}
                        <a href="#portfolio-sec" class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".5s">
                            <i class="fa fa-recycle icon-round icon-round-active">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                            </i>
                            <h3 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".6s">PRODUITS </h3>
                        </a>
                        {% endcomment %}
                        <a href="{% url 'commerce:index' %}" class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".7s">
                            <i class="fa fa-paper-plane-o icon-round">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </i>
                            <h3 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".8s">VISITE DU SITE</h3>
                        </a>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-5 text-center">
                        <img src="{% static 'images/home/girl2.jpg' %}" class="main-img-2 img-circle wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".2s" alt="" />
                        <h1 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".4s">MEILLEURS</h1>
                        <h2 class="wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".6s">PRIX DE GROS</h2>
                        <a href="{% url 'sign_up' %}" class="btn custom-btn-one btn-lg wow bounceIn animated" data-wow-duration="1s" data-wow-delay=".8s">S'INSCRIRE</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
        <!--  JQUERY CORE SCRIPTS -->
    <script src="assets/js/jquery-1.10.2.js"></script>
    <!--  BOOTSTRAP SCRIPTS -->
    <script src="assets/js/bootstrap.js"></script>
    <!--  SCROLL SCRIPTS -->
    <script src="assets/js/jquery.easing.min.js"></script>
    <!--  WOW ANIMATION SCRIPTS -->
    <script src="assets/js/wow.min.js"></script>
    <!-- EASY PIE CHART SCRIPTS -->
    <script src="assets/js/jquery.easypiechart.min.js"></script>
    <!-- PRETTY PHOTO SCRIPTS -->
    <script src="assets/js/jquery.prettyPhoto.js"></script>
    <!--  STYLE SWITCHER SCRIPTS -->
    <script src="assets/js/styleSwitcher.js"></script>
    <!--  CUSTOM SCRIPTS -->
    <script src="assets/js/custom.js"></script>
    
</body>
</html>