commerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'commerce.views.splash', name='splash'),
    url(r'^home$', 'commerce.views.index', name='index'),
    # url(r'^$', 'commerce.views.index', name='index'),
    url(r'^information/$', 'commerce.views.information', name='information'),    
    url(r'^condition/$', 'commerce.views.condition', name='condition'),    
    
    url(r'^category/$', 'commerce.views.display_category_random', name='display_category_random'),
    url(r'^category/(?P<category_id>\d+)/$', 'commerce.views.display_category', name='display_category'),
    url(r'^product-min-price/$', 'commerce.views.display_product_min_price', name='display_product_min_price'),
    url(r'^product-min-moq/$', 'commerce.views.display_product_min_moq', name='display_product_min_moq'),
    url(r'^product/(?P<product_id>\d+)/$', 'commerce.views.display_product', name='display_product'),
    
    url(r'^account/profile/$', 'commerce.views.account', name='account'),
    url(r'^order/$', 'commerce.views.display_order', name='display_order'),
    url(r'^add-address/$', 'commerce.views.add_address', name='add_address'),
    url(r'^addresses/$', 'commerce.views.addresses', name='addresses'),
    url(r'^remove-addresses/(?P<address_id>\d+)/$', 'commerce.views.remove_address', name='remove_address'),
    
    url(r'^cart/(?P<product_id>\d+)/(?P<qty>\d+)/$', 'commerce.views.add_to_cart', name='cart'),
#     url(r'^remove-from-cart/(?P<product_id>\d+)/$', 'commerce.views.remove_from_cart', name='remove_from_cart'),
    url(r'^shipping/(?P<product_id>\d+)/$', 'commerce.views.shipping', name='shipping'),
    
    url(r'^shipping-special/$', 'commerce.views.shipping_special', name='shipping_special'),
    
    url(r'print-contrat/(?P<order_id>\d+)/$', 'commerce.views.print_contrat', name='print_contrat'),
    
    url(r'^display-users/$', 'commerce.views.display_users', name='display_users'),
    url(r'^display-user-order/(?P<id>\d+)/$', 'commerce.views.display_users_order', name='display_users_order'),
    url(r'^display-users-order/special/$', 'commerce.views.display_users_order_special', name='display_users_order_special'),
    url(r'^display-user-order/special/validate/(?P<id>\d+)/$', 'commerce.views.users_order_special_validate', name='users_order_special_validate'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

okayproject/urls.py
from commerce.views import SignUpView, SignOutView, SignInView

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^account/sign-in/$', SignInView.as_view(), name='sign_in'),
    url(r'^account/sign-up/$', SignUpView.as_view(), name='sign_up'),
    url(r'^account/sign-out/$', SignOutView.as_view(), name='sign_out'),
    
    url(r'', include('commerce.urls', namespace='commerce', app_name='commerce')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

from commerce.models import Address, OrderSpecial

class UsersCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=100, required=True)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email',]

class AddAddress(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
        exclude = ['user']

class AddParticularAddress(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    cin = forms.CharField(required=False)
    
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
        exclude = ['user', 'company', 'company_form', 'nif']

class AddSocietyAddress(forms.ModelForm):
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    nif = forms.CharField(required=False)
    
    company = forms.CharField(label='Raison social', required=False)
    company_form = forms.CharField(label='Forme', required=False)
    cin = forms.CharField(required=False)
    nif = forms.CharField(required=False)
    
    class Meta:
        model = Address
#         fields = '__all__'
        exclude = ['user', 'gender', 'first_name', 'last_name', 'cin']
        

class OrderSpecialForm(forms.ModelForm):
#     name = forms.CharField(max_length=100, required=True)
#     short_desc = forms.CharField(max_length=100, required=False)
#     long_desc = forms.CharField(max_length=100, required=False)
     
    class Meta:
        model = OrderSpecial
        fields = ['name', 'short_desc', 'long_desc', 'quantity', 'thumbnail',]
        exclude = ['user']

commerce/views.py
# -*- coding:utf-8 -*-

from commerce.models import *
from commerce.forms import *

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse

from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
from io import BytesIO
from django.contrib.auth.models import User

import datetime
import random
from datetime import date
import time

# Create your views here.

def slide_all_product():
    products = list()
    count = Product.objects.count()
    p = Product.objects.order_by('price').filter(date_validity__gte=datetime.datetime.now())
    i = 0
    while i < count:
        products.append(p[i:(i+3)])
        i += 3

    return products

def initialize_product_data():
    products = Product.objects.all()
    for product in products:
        if datetime.date.today().__ge__(product.date_validity):
            product.qty_commanded = 0
            product.save()

def splash(request):
    return render(request, 'spash.html')

def index(request):
    products = Product.objects.order_by('-id').filter(date_validity__gte=datetime.datetime.now())
    products_slide = slide_all_product()
    categories_list = Category.objects.all()

    address_count = Address.objects.filter(user_id=request.user.id).count()
    if request.user.is_authenticated():
        if request.user.is_superuser:
            user_count = User.objects.all().count() - 1
            orders = Order.objects.order_by('-id').filter()
            orders_valide = Order.objects.filter(status='Valide').order_by('-date_validated')
            orders_waite = Order.objects.filter(status='En attente').order_by('-date_validated')
            initialize_product_data()
            return render(request, 'admin_okay/index.html', locals())
        else:
            order_special = OrderSpecial.objects.filter(user_id=request.user.id, status='Valide').count()
            if order_special > 0:
                messages.add_message(request, messages.INFO, "Vous avez des commandes spéciale validé <br>\
                Nous vous informons par e-mail la suite de votre commande spéciale")
    
    return render(request, 'index.html', locals())

# -------------------------------------
# user connexion
# -------------------------------------

def information(request):
    products = Product.objects.filter(date_validity__lte=datetime.datetime.now()).order_by('-id')[:6]
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    return render(request, 'information.html', locals())

def condition(request):
    products = Product.objects.filter(date_validity__lte=datetime.datetime.now()).order_by('-id')[:6]
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    return render(request, 'condition.html', locals())

class SignUpView(generic.CreateView):
    form_class = UsersCreationForm
    model = User
    success_url = reverse_lazy('commerce:index')
    template_name = 'account/sign_up.html'
    
    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO,
                             'Vous ête actuellement membre du site! Connectez à votre compte à fin d\'effectuer des commandes')
        return super(SignUpView, self).form_valid(form)
    
class SignInView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('commerce:index')
    template_name = 'account/sign_in.html'
    
    
    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        
        if user is not None and user.is_active:
            login(self.request, user)
            return super(SignInView, self).form_valid(form)
        else:
            return self.form_invalid(form)
        
class SignOutView(generic.RedirectView):
    url = reverse_lazy('sign_in')
    
    def get(self, request):
        logout(request)
        return super(SignOutView, self).get(request)

def account(request):
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.username = request.POST['username']
        
#         if user.check_password(request.POST['password1']):
#             user.set_password(request.POST['password2'])
#         else:
#             messages.add_message(request, messages.ERROR, "Password invalide. Veuillez saisir votre ancien password")
        
        user.save()
        
    return render(request, 'account/account.html', locals())

# product & category

def display_category(request, category_id):
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    category = get_object_or_404(Category, pk=category_id)
    product_list = category.all_products()
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/category.html', locals())

def display_category_random(request):
    categories_list = Category.objects.all()
    x = random.randint(0, categories_list.count()-1)
    category_id = categories_list[x].id
    category = get_object_or_404(Category, pk=category_id)
    product_list = category.all_products()
    paginator = Paginator(product_list, 4)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/category.html', locals())

def display_product_min_price(request):
    title = 'Produits moins chère'
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
#     product_list = Product.objects.order_by('price')
    product_list = Product.objects.order_by('price').filter(date_validity__gte=datetime.datetime.now())
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/product_min.html', locals())

def display_product_min_moq(request):
    title = 'Produit avec une MOQ minimum'
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
#     product_list = Product.objects.order_by('moq')
    product_list = Product.objects.order_by('moq').filter(date_validity__gte=datetime.datetime.now())
    paginator = Paginator(product_list, 12)
    products_slide = slide_all_product()
 
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
 
    return render(request, 'commerce/product_min.html', locals())


def display_product(request, product_id):
#     id = request.session['cart'].get('product_qty')
    product = get_object_or_404(Product, pk=product_id) 
    products_slide = slide_all_product()
    categories_list = Category.objects.all()
    address_count = Address.objects.filter(user_id=request.user.id).count()
    
    if request.method == 'POST':
        quantity = request.POST['quantity']        
        if Cart.objects.filter(user_id=request.user.id, product_id=product_id).exists():
            cart = Cart.objects.get(user_id=request.user.id, product_id=product_id)
            cart.quantity = request.POST['quantity']
        else:
            cart = Cart(user_id=request.user.id, product_id=product_id, quantity=int(request.POST['quantity']))

        cart.save()
                
        return render(request, 'commerce/cart.html', locals())
    
    return render(request, 'commerce/product.html', locals())

# orders

def confirmation(request):
    pass

def shipping(request, product_id):
    categories_list = Category.objects.all()
    addresses = Address.objects.filter(user_id=request.user.id)
    cart = Cart.objects.get(user_id=request.user.id, product_id=product_id)
    
    if request.method == 'POST':
        order = Order(product_id=product_id,
                      user_id=request.user.id,
                      address_id=request.POST['shipping_address'],
                      quantity=cart.quantity)
        
        product = Product.objects.get(id=product_id)

commerce/templates/commerce/cart.html
{% extends "layout.html" %}

{% block title %}Mon panier{% endblock %}

{% block content %}
<section id="cart_items">
        
        <div class="table-responsive cart_info">
            
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Produit</td>
                        <td class="description"></td>
                        <td class="price">Prix fournisseur</td>
                        <td class="quantity">Quatité commandé</td>
                        <td class="total">Total fournisseur</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    <!--  -->
                    <tr>
                        <td class="cart_product">
                            <img src="{{ MEDIA_URL }}{{ cart.product.thumbnail }}" width="100px"></img>
                        </td>
                        <td class="cart_description">
                            <a href="#"><h5>{{ cart.product.name }}</h5></a>
                            <p><small>{{ cart.product.short_desc }}</small></p>
                        </td>
                        <td class="cart_price">{{ cart.product.price }} AR</td>
                        <td class="cart_quantity">{{ cart.quantity }}</td>
                        <td class="cart_total">{{ cart.total }} AR</td>
                        <td class="cart_delete">
                            <a class="btn btn-primary" href="{% url 'commerce:display_product' cart.product.id %}"><i class="fa fa-times"></i></a>
                        </td>
                    </tr>
                <!--  -->
                </tbody>
            </table>
        </div>
    
    <div class="pull-right">
        <a href="{% url 'commerce:shipping' cart.product_id %}" class="btn btn-primary">
            Suivant 
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
</section>
<!--  -->
        

{% endblock %}

commerce/templates/commerce/category.html
{% extends "layout.html" %}

{% load static %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}


<section>
    <div class="row">
        {% include "side-bar.html" %}
                
        <div class="features_items"><!--features_items-->
            <h2 class="title text-center">{{ category.name }}</h2>
            <div class="row">
                 {% for product in products %}
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img class="produit-thumbnail" src="{{ MEDIA_URL }}{{ product.thumbnail }}"  class="thumbnail" alt="" />
                                <h2>{{ product.price }} AR</h2>
                                <p class="product-name" >{{ product.name }}</p>
                            </div>
                            <div class="product-overlay">
                                <div class="overlay-content">
                                    <h2>{{ product.price }} AR</h2>
                                    <p class="product-name">{{ product.name }}</p>
                                    <a href="{% url 'commerce:display_product' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-eye -open"></i>Details / Commandes</a>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                {% empty %}
                <div class="col-sm-12">
                    <div class="alert alert-warning" role="alert">
                        <i class="fa fa-shopping-cart fa-3x pull-left"></i> <h4>Pas de produit :(</h4>
                        <p>Acune produit disponible sur cette catégoire pour le moment</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <nav>
                    <ul class="pagination">
                        {% if products.has_previous %}
                            <li class="previous"><a href="?page={{ products.previous_page_number }}">page précédente</a></li>
                        {% endif %}
                        <li class="disabled"><a href="#">Page {{ products.number }} sur {{ products.paginator.num_pages }}</a></li>
                        {% if products.has_next %}
                            <li><a href="?page={{ products.next_page_number }}"> page suivante</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        
    </div>
</section>
{% endblock %}

commerce/templates/commerce/checkout.html
{% extends "layout.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}
<section>
    <p class="text-info"><i class="fa fa-3x fa-info-circle pull-left"></i>
        Pour le produit {{ product.name }}, la quantité minimum pour la commande au fournisseur est de 
        {{ product.moq }}. 
    </p>
</section>
{% endblock %}

commerce/templates/commerce/particular_form.html
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">{% bootstrap_field add_address_form.gender %}</div>
        </div>
        <div class="row">
            <div class="col-md-6">{% bootstrap_field add_address_form.last_name %}</div>
            <div class="col-md-6">{% bootstrap_field add_address_form.first_name %}</div>
        </div>
        <div class="row">
            <div class="col-md-6">{% bootstrap_field add_address_form.address %}</div>
            <div class="col-md-6">{% bootstrap_field add_address_form.cin %}</div>
        </div>
        <div class="row">
            <div class="col-md-6">{% bootstrap_field add_address_form.postcode %}</div>
            <div class="col-md-6">{% bootstrap_field add_address_form.city %}</div>
        </div>
        <div class="row">
            <div class="col-md-12">{% bootstrap_field add_address_form.phone %}</div>
        </div>
    </div>
</div>

commerce/templates/commerce/product_min.html
{% extends "layout.html" %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}


<section>
    <div class="row">
        {% include "side-bar.html" %}
                
        <div class="features_items"><!--features_items-->
            <h2 class="title text-center">{{ title }}</h2>
            <div class="row">
                 {% for product in products %}
                <div class="col-sm-4">
                    <div class="product-image-wrapper">
                        <div class="single-products">
                            <div class="productinfo text-center">
                                <img class="produit-thumbnail" src="{{ MEDIA_URL }}{{ product.thumbnail }}"  class="thumbnail" alt="" />
                                <h2>{{ product.price }} MGA</h2>
                                <p class="product-name" >{{ product.name }}</p>
                            </div>
                            <div class="product-overlay">
                                <div class="overlay-content">
                                    <h2>{{ product.price }} MGA</h2>
                                    <p class="product-name">{{ product.name }}</p>
                                    <a href="{% url 'commerce:display_product' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-eye -open"></i>Details / Commandes</a>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                {% empty %}
                <div class="col-sm-12">
                    <div class="alert alert-warning" role="alert">
                        <i class="fa fa-shopping-cart fa-3x pull-left"></i> <h4>Pas de produit :(</h4>
                        <p>Acune produit disponible sur cette catégoire pour le moment</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <nav>
                    <ul class="pagination">
                        {% if products.has_previous %}
                            <li class="previous"><a href="?page={{ products.previous_page_number }}">page précédente</a></li>
                        {% endif %}
                        <li class="disabled"><a href="#">Page {{ products.number }} sur {{ products.paginator.num_pages }}</a></li>
                        {% if products.has_next %}
                            <li><a href="?page={{ products.next_page_number }}"> page suivante</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        
    </div>
</section>
{% endblock %}

commerce/templates/commerce/shipping.html
{% extends "layout.html" %}

{% block title %}Confirmation de commande{% endblock%}

{% block content %}  
<section id="cart_items">
    <form method="post" action=".">
        <div class="row">
            {% csrf_token %}
            
            <h3>Mes rensignements de commande</h3>
            <small>
                <a class="pull-right" href="{% url 'commerce:add_address' %}?next={% url 'commerce:shipping' cart.product_id %}">
                    <i class="fa fa-plus"></i> Ajouter une renseignement
                </a>
            </small>
            
            {% if addresses %}
                <p class="text-info">Choisir votre renseignement pour cette commande ou ajouter un nouveau.</p>
            {% endif %}

            {% for address in addresses %}
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <input type="radio" name="shipping_address" id="shipping_address_{{ forloop.counter }}"
                               value="{{ address.id }}" {% if forloop.counter == 1 or shipping_address == address.id %}checked{% endif %}>
                            {% if address.type == 'Particulier' %}                                    
                                {{ address.first_name }} {{ address.last_name }}
                            {% else %}                                    
                                {{ address.company }} {{ address.company_form }}
                            {% endif %}
                            <small>&laquo; {{ address.type }} &raquo;</small>
                        </h4>
                    </div>
                    <div class="panel-body">
                        <p>
                        {{ address.address }}<br>
                        {{ address.city }} - {{ address.postcode }}
                        </p>
                    </div>
                </div>            
            </div>
            {% empty %}
                <p class="text-info"><i class="fa fa-3x fa-info-circle pull-left"></i>Vous n'avez pas encore de renseignement pour votre compte client.
                <br />Pour commander, commencez par ajouter un renseignement en cliquant sur le bouton le lien ajouter.</p>
            {% endfor %}
        </div>
        
        <div class="row">
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                        <tr class="cart_menu">
                            <td class="image">Produit</td>
                            <td class="description"></td>
                            <td class="price">Prix fournisseur</td>
                            <td class="quantity">Quatité commandé</td>
                            <td class="total">Total fournisseur</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <!--  -->
                        <tr>
                            <td class="cart_product">
                                <img src="{{ MEDIA_URL }}{{ cart.product.thumbnail }}" width="100px"/>
                            </td>
                            <td class="cart_description">
                                <h4>{{ cart.product.name }}</h4>
                                <small>{{ cart.product.short_desc }}</small>
                            </td>
                            <td class="cart_price">{{ cart.product.price }} AR</td>
                            <td class="cart_quantity">{{ cart.quantity }}</td>
                            <td class="cart_total">{{ cart.total }} AR</td>
                            <td class="cart_delete">
                                <a class="btn btn-primary" href="{% url 'commerce:display_product' cart.product.id %}"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    <!--  -->
                    </tbody>
                </table>
            </div>
        </div>
        
        {% if addresses %}
        <div class="row">
            <h3>Engagement du client</h3>
            <small>
                <p class="text-info">
                    <input type="checkbox" name="accepte_terme">
                    Cocher cette case si vous acceptez ce terme.
                </p>
            </small>
                          
            <ol>
                <li>La durée de validité de cette souscription est de {{ cart.product.date_validity }}.</li>
                <li>OKAY TRADING mettra tout en oeuvre afin de faire d'atteindre le MOQ nécessaire au lancement de la commande.</li>
                <li>Le client s'engage a honorer la souscription en cas d'atteinte des MOQ.</li>
            </ol>
            <b>Je m'engage a honoré cette souscription en cas d'atteinte des MOQ.</b>
        
            <p>Le contrat de commande sera enregistrer sous forme de pdf.</p>
            <button type="submit" class="btn btn-primary pull-right" name="register" id="confirme">
                Confirmer ma commande</a>
            </button>
        </div>
        {% endif %}

    </form>
</section>

{% endblock %}

{% block script %}
    <script>
        $(document).ready(function() {
            $("#confirme").hide();
            $("input:checkbox").click(function() {
                var x = $("input[name='accepte_terme']:checked").val()
                <!-- alert(x); -->
                if(x == 'on') {
                    $("#confirme").show();
                }
                else {
                    $("#confirme").hide();
                }
            });
        });
    </script>
{% endblock %}

commerce/templates/commerce/society_form.html
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">{% bootstrap_field add_address_form.company %}</div>
            <div class="col-md-6">{% bootstrap_field add_address_form.company_form %}</div>
        </div>
        <div class="row">
            <div class="col-md-6">{% bootstrap_field add_address_form.address %}</div>
            <div class="col-md-6">{% bootstrap_field add_address_form.nif %}</div>
        </div>
        <div class="row">
            <div class="col-md-6">{% bootstrap_field add_address_form.postcode %}</div>
            <div class="col-md-6">{% bootstrap_field add_address_form.city %}</div>
        </div>
        <div class="row">
            <div class="col-md-12">{% bootstrap_field add_address_form.phone %}</div>
        </div>
    </div>
</div>